# Generated by Django 3.0.5 on 2022-09-24 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('heartbeat', models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
