# Generated by Django 4.1.1 on 2022-09-24 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='heartbeat',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(300, message="Heartbeat can't be greater than 300"), django.core.validators.MinValueValidator(1, message="Heartbeat can't be smaller than 1")]),
        ),
    ]
